### ISSUE TITLE
Aggregate Functions Cypher

### ISSUE THREAD

**Issue by jnayak1** [aplbrain/grand-cypher#39]
Awesome library! Exactly what i needed. Aggregate functions don't seem to work though
https://neo4j.com/docs/cypher-manual/current/functions/aggregating/

**Comment by j6k4m8** [comment]
@jnayak1 looks like the amazing @jackboyla has fixed this in #45! give it a look and see if we can close this issue?

**Comment by j6k4m8** [comment]
(oops, didn't mean to close yet!)
