### ISSUE TITLE
WHERE-clause boolean algebra

### ISSUE THREAD

**Issue by j6k4m8** [aplbrain/grand-cypher#6]
This involves AND/OR/NOT support (with order-of-operations to match that of Cypher) with parentheses. I think this might be pretty complicated because it will entail backtracking the entire structural match if clauses aren't met; it might make more sense to run `OR` operands in parallel, so that 

```
MATCH (A)
WHERE (A.type = 1 AND B.type = 1) OR (B.type = 2)
RETURN A
```

becomes two queries:

```
MATCH (A)
WHERE (A.type = 1 AND B.type = 1)
RETURN A
```

```
MATCH (A)
WHERE (B.type = 2)
RETURN A
```

But I imagine this will get much more complicated for deeper nesting.

**Comment by khoale88** [comment]
support is added. Lucky that I had some experience.
